#Your list of all species
species_file : inputFiles/default_species.csv

#core reactions from gas phase database
database_reaction_file : inputFiles/umist12-ucledit.csv
database_reaction_type : UMIST
#database_reaction_file : inputFiles/kida.uva.2014.dat
#database_reaction_type : KIDA

#set of additional reactions: eg grain network
custom_reaction_file : inputFiles/default_grain_network.csv
custom_reaction_type : UCL

#whether to automatically expand to three phase network
three_phase : True

# Directory in which to store output. If not included we automatically move
# the files to the uclchem src folder. This is the default behaviour.
# output_directory : "outputFiles"
