#Your list of all species
species_file: data/default/default_species.csv

#core reactions from gas phase database
database_reaction_file: data/databases/umist22.csv
database_reaction_type: UMIST
# database_reaction_file : data/databases/gas_reactions_kida.uva.2024.in
# database_reaction_type : KIDA

#set of additional reactions: eg grain network
custom_reaction_file: data/default/default_grain_network.csv
custom_reaction_type: UCL

# Directory in which to store output. If not included we automatically move
# the files to the uclchem src folder. This is the default behaviour.
# output_directory : "outputFiles"

# Enable to add gas-phase CRP, CRPHOT and PHOTON reactions to grains as well
# Be aware that this will cause stiffness, see tests/test_photo_on_grains.py for 
# solver settings that should work for static, stage 1 and stage 2 models.
add_crp_photo_to_grain: False
# Enable the writing of the rates and flux to the disk
enable_rates_to_disk: True
# Enable the computation of all the enthalpies:
add_delta_enthalpy: ALL